# Generated by Django 5.2 on 2026-03-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('PURCHASED', 'Purchased')], default='AVAILABLE', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.session')),
            ],
        ),
    ]
